os:
  - linux
  - osx
matrix:
  include:
    -language: node.js
     node_js:
     - '11.10'
     cache:
     - npm
     - yarn
     before_install:
     - cd faucet-ui
     install:
     - travis_retry yarn install
     script:
     - yarn build
     - yarn test

     -language: swift
     before_install:
     - cd faucet-service 
     - brew update
     - brew install vapor
     script:
     - swift run
     - swift test
     