sudo: required
matrix:
  include:
    - language: swift
      os: osx
      before_install:
        - cd faucet-service 
        - brew update
        - brew tap vapor/tap
        - brew install vapor/tap/vapor
      script:
        - swift test
    - language: node.js
      node_js:
        - "node"
      before_script:
        - cd faucet-ui
        - yarn install
      script:
        - yarn build
        - yarn test
        