language: generic
sudo: required
os: osx
matrix:
  include:
    - language: swift
      before_install:
        - cd faucet-service 
        - brew update
        - brew tap vapor/tap
        - brew install vapor/tap/vapor
      script:
        - swift test
    - language: node.js
      node_js:
        - '11.10'
      before_install:
        - cd faucet-ui
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - travis_retry yarn install
      script:
        - yarn build
        - yarn test
        