version: '3'
services:
   nginx:
    image: nginx:latest
    expose:
     - "80"
    ports:
     - "9000:3000"
    volumes:
    # 映射nginx.conf文件到容器的/etc/nginx/conf.d目录并覆盖default.conf文件
     - ./faucet-ui/nginx.conf:/etc/nginx/conf.d/default.conf
    # 映射build文件夹到容器的/usr/share/nginx/html文件夹
     - ./facet-ui/build:/usr/share/nginx/html
    # 覆盖容器启动后默认执行的命令。
    command: /bin/bash -c "nginx -g 'daemon off;'"
   faucet:
    build:
      context: ./faucet-server
      dockerfile: ./Dockerfile
      args:
       - ENVIRONMEN=dev
       - GITHUB_OAUTH_CLIENT_ID=
       - GITHUB_OAUTH_CLIENT_SECRET=
    ports:
      - "9001:80"
